config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path, re_path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

from rocket_connect import __version__ as ROCKET_CONNECT_VERSION
from rocket_connect.instance import views

admin.site.site_header = "Rocket Connect " + ROCKET_CONNECT_VERSION
admin.site.site_title = "Rocket Connect " + ROCKET_CONNECT_VERSION

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("rocket_connect.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("instance/", include("rocket_connect.instance.urls", namespace="instance")),
    re_path(
        r"^connector/(?P<connector_id>\w+)/inbound/?$", views.connector_inbound_endpoint
    ),
    re_path(r"^connector/(?P<connector_id>\w+)/?$", views.connector_endpoint),
    re_path(r"^server/(?P<server_id>\w+)/?$", views.server_endpoint),
    re_path(r"^server/(?P<server_id>\w+)/messages/?$", views.server_messages_endpoint),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

rocket_connect/instance/urls.py
from django.urls import re_path

from rocket_connect.instance.views import active_chat
from rocket_connect.instance.views import connector_analyze
from rocket_connect.instance.views import new_chatwoot_connector
from rocket_connect.instance.views import new_rocketchat_connector
from rocket_connect.instance.views import new_server
from rocket_connect.instance.views import new_server_chatwoot
from rocket_connect.instance.views import new_server_rocket_chat
from rocket_connect.instance.views import server_detail_view
from rocket_connect.instance.views import server_monitor_view

app_name = "instance"
urlpatterns = [
    re_path(
        r"^server/(?P<server_id>\w+)/monitor/?$",
        view=server_monitor_view,
        name="server_monitor",
    ),
    re_path(
        r"^server/(?P<server_id>\w+)/?$",
        view=server_detail_view,
        name="server_detail",
    ),
    re_path(
        r"^server/(?P<server_id>\w+)/active-chat/?$",
        view=active_chat,
        name="active_chat",
    ),
    re_path(
        r"^server/(?P<server_id>\w+)/analyze/(?P<connector_id>\w+)/?$",
        view=connector_analyze,
        name="connector_analyze",
    ),
    re_path(
        r"^server/(?P<server_id>\w+)/new/rocketchat/connector/?$",
        view=new_rocketchat_connector,
        name="new_rocketchat_connector",
    ),
    re_path(
        r"^server/(?P<server_id>\w+)/new/chatwoot/connector/?$",
        view=new_chatwoot_connector,
        name="new_chatwoot_connector",
    ),
    re_path(
        r"^new/server/?$",
        view=new_server,
        name="new_server",
    ),
    re_path(
        r"^new/server/rocketchat/?$",
        view=new_server_rocket_chat,
        name="new_server_rocketchat",
    ),
    re_path(
        r"^new/server/chatwoot/?$",
        view=new_server_chatwoot,
        name="new_server_chatwoot",
    ),
]

rocket_connect/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

rocket_connect/envelope/views.py
# from django.shortcuts import render

# Create your views here.

rocket_connect/instance/views.py
import datetime
import json
import uuid

import pytz
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.db.models import Max
from django.db.models import Q
from django.db.models.functions import TruncDay
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.shortcuts import reverse
from django.views.decorators.csrf import csrf_exempt
from envelope.models import LiveChatRoom
from instance.forms import NewConnectorForm
from instance.forms import NewServerForm
from instance.models import Connector
from instance.models import Server

from .forms import NewChatwootConnectorForm
from .forms import NewChatwootServerForm
from .forms import NewInboundForm


@csrf_exempt
def connector_endpoint(request, connector_id):
    connector = get_object_or_404(
        Connector,
        external_token=connector_id,
        enabled=True,
        server__enabled=True,
    )
    return_response = connector.intake(request)
    if not (return_response):
        return JsonResponse(
            {
                "connector_name": connector.name,
                "connector_id": connector.external_token,
            },
        )
    return return_response


@csrf_exempt
def connector_inbound_endpoint(request, connector_id):
    connector = get_object_or_404(
        Connector,
        external_token=connector_id,
        enabled=True,
        server__enabled=True,
    )
    return_response = connector.inbound_intake(request)
    if not return_response:
        return HttpResponse("No inbound return.", status=404)
    # it can request a redirect
    if return_response.get("redirect"):
        return redirect(return_response["redirect"])
    if return_response.get("notfound"):
        return HttpResponse(return_response.get("notfound"), status=404)
    return JsonResponse(return_response)


# Custom decorator
def must_be_yours(func):
    def check_and_call(request, *args, **kwargs):
        server_id = kwargs["server_id"]
        servers_owned = request.user.servers.all().values_list(
            "external_token",
            flat=True,
        )
        if server_id not in servers_owned:
            return redirect(reverse("home"))
        return func(request, *args, **kwargs)

    return check_and_call


@csrf_exempt
def server_endpoint(request, server_id):
    server = get_object_or_404(Server, external_token=server_id, enabled=True)
    if server.type == "rocketchat":
        # default_messages check
        if request.GET.get("default_messages"):
            return JsonResponse(server.default_messages, safe=False)
        # unauthorized access
        # if no server.secret_token, allow unprotected access
        if (
            server.secret_token
            and request.headers.get("X-Rocketchat-Livechat-Token")
            != server.secret_token
        ):
            # alert manager channel
            server.multiple_connector_admin_message(
                ":warning:  Rocket.Chat Omnichannel Connection Test was Received."
                + "It was *not successfull*, as the secret token is different",
            )
            return HttpResponse(
                "Unauthorized. No X-Rocketchat-Livechat-Token provided.",
                status=401,
            )
        # income message, we have a body
        if request.body:
            raw_message = json.loads(request.body)

            #
            # roketchat test message
            #
            if raw_message.get("_id") == "fasd6f5a4sd6f8a4sdf":
                message_sent = server.multiple_connector_admin_message(
                    ":white_check_mark:  Rocket.Chat Omnichannel Connection Test was Received. This is the response.",
                )
                if message_sent:
                    return JsonResponse({})
                else:
                    return HttpResponse(
                        "Unauthorized. No X-Rocketchat-Livechat-Token provided.",
                        status=401,
                    )
            else:
                # process ingoing message
                try:
                    room = LiveChatRoom.objects.get(room_id=raw_message["_id"])
                except LiveChatRoom.DoesNotExist:
                    # todo: Alert Admin that there was an attempt to message a non existing room
                    # todo: register this message somehow. RCHAT will try to deliver it a few times
                    # do not answer 404 as rocketchat will keep trying do deliver
                    return HttpResponse("Room Not Found", status=200)
                except LiveChatRoom.MultipleObjectsReturned:
                    # this situation hangs RocketChat forever
                    room = LiveChatRoom.objects.filter(
                        room_id=raw_message["_id"],
                    ).first()

                # now, with a room, or at least one of them, let's keep it going
                Connector = room.connector.get_connector_class()
                connector = Connector(room.connector, request.body, "ingoing", request)
                connector.room = room
                # call primary connector
                connector.ingoing()
                # call secondary connectors for ingoing
                for secondary_connector in room.connector.secondary_connectors.all():
                    SConnector = secondary_connector.get_connector_class()
                    sconnector = SConnector(
                        secondary_connector,
                        request.body,
                        "ingoing",
                        request,
                    )
                    connector.logger_info(
                        f"RUNING SECONDARY CONNECTOR *{sconnector.connector}* WITH BODY {request.body}:",
                    )
                    sconnector.ingoing()
    if server.type == "chatwoot":
        # for chatwoot, the outgoing messages will also be sent to the connector
        # here we only will receive the ROCKETCONNECT INBOX payalods
        # so we need to find the connector, based on source_id
        print("INCOMING ON CHATWOOT", request.body)
        raw_message = json.loads(request.body).get("conversation")
        if raw_message.get("messages", {}):
            content = raw_message.get("messages", {})[0].get("content")
            connector_conversation_id = raw_message.get("id")
            connector_instance = server.connectors.get(
                config__connector_conversation_id=connector_conversation_id,
            )
            Connectorcls = connector_instance.get_connector_class()
            connector = Connectorcls(
                connector_instance,
                request.body,
                "ingoing",
                request,
            )
            if content == "status":
                status_session = connector.status_session()
                connector.outcome_admin_message(status_session)
            if content == "start":
                initialize = connector.initialize()
                connector.outcome_admin_message(initialize)
            if content == "close":
                status_session = connector.status_session()
                close = connector.close_session()
                connector.outcome_admin_message(close)

    return JsonResponse({})


@csrf_exempt
def server_messages_endpoint(request, server_id):
    server = get_object_or_404(Server, external_token=server_id, enabled=True)
    messages = server.get_custom_messages(term=request.GET.get("term"))
    return JsonResponse(list(messages), safe=False)


@login_required(login_url="/accounts/login/")
@must_be_yours
def active_chat(request, server_id):
    server = get_object_or_404(Server.objects, external_token=server_id)
    form = NewInboundForm(request.POST or None, server=server)
    # get online agents and departments
    rocket = server.get_rocket_client()
    departments_raw = rocket.call_api_get("livechat/department").json()
    departments_choice = [
        ("@" + d["name"], "Department: " + d["name"])
        for d in departments_raw["departments"]
    ]
    destinations = departments_choice
    # now get online agents
    agents = rocket.livechat_get_users(user_type="agent").json()
    available_agents = [
        agent["username"]
        for agent in agents["users"]
        if agent["status"] == "online" and agent["statusLivechat"] == "available"
    ]
    print(available_agents)
    for agent in available_agents:
        destinations.append(("@" + agent, "Agent: " + agent))

    form.fields["destination"].choices = destinations
    if form.is_valid():
        pass
    context = {"server": server, "form": form}
    return render(request, "instance/active_chat.html", context)


@login_required(login_url="/accounts/login/")
@must_be_yours
def server_detail_view(request, server_id):
    server = get_object_or_404(Server.objects, external_token=server_id)
    room_sync = None
    delivered_messages_to_delete = None
    # get server status
    status = server.status()
    if request.GET.get("force_connector_delivery"):
        connector = get_object_or_404(
            server.connectors,
            external_token=request.GET.get("force_connector_delivery"),
        )
        # TODO: do as task
        undelivered_messages = connector.messages.filter(delivered=False)
        for message in undelivered_messages:
            message.force_delivery()
            if message.delivered:
                messages.success(
                    request,
                    f"Sucess! Message #{message.id} was delivered at connector {message.connector.name}",
                )
            else:
                messages.error(
                    request,
                    f"Error! Could not deliver Message #{message.id} at connector {message.connector.name}",
                )

rocket_connect/users/api/views.py
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin
from rest_framework.mixins import RetrieveModelMixin
from rest_framework.mixins import UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from rocket_connect.users.models import User

from .serializers import UserSerializer


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

rocket_connect/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from rocket_connect.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        # for mypy to know that the user is authenticated
        assert self.request.user.is_authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

rocket_connect/templates/instance/active_chat.html
{% extends "base.html" %}

{% load parse_date crispy_forms_tags %}

{% block content %}
  <nav class="breadcrumb">
    <a class="breadcrumb-item" href="{% url 'home' %}">home</a>
    <span class="breadcrumb-item"><a href="{% url 'instance:server_detail' server.external_token %}">{{ server }}</a></span>
    <span class="breadcrumb-item active">Active Chat</span>
  </nav>
  {{ form|crispy }}
{% endblock content %}

rocket_connect/templates/instance/connector_analyze.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
  <nav class="breadcrumb">
    <a class="breadcrumb-item" href="{% url 'home' %}">home</a>
    <span class="breadcrumb-item">
      <img src="{{ connector.server.get_icon }}" width="20px" alt="server icon" />
      <a href="{% url 'instance:server_detail' connector.server.external_token %}">{{ connector.server }}</a>
    </span>
    <span class="breadcrumb-item active">{{ connector }}</span>
  </nav>
  <h3>
    <span class="badge bg-info float-end badge-lg">{{ connector.connector_type }}</span>
  </h3>
  <h1>
    {% if request.user.is_staff %}
      <a name=""
         class="btn btn-primary"
         href="{% url 'admin:instance_connector_change' connector.id %}"
         role="button">
        <i class="fa fa-edit" aria-hidden="true"></i> Edit
      </a>
    {% endif %}
    <a name=""
       class="btn btn-primary"
       href="?check-room-sync=1"
       role="button"
       title="Sync Rooms">
      <i class="fas fa-recycle"></i> Sync
    </a>
    {{ connector }}
    <span class="text-{{ connector.enabled|yesno:'success,danger' }}">{{ connector.enabled|yesno:"Active,Inactive" }}</span>
  </h1>
  Endpoint: {{ base_uri }}/connector/{{ connector.external_token }}/
  {% if room_sync %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <button type="button"
              class="btn-close"
              data-bs-dismiss="alert"
              aria-label="Close"></button>
      <strong>Unsync Rooms:</strong>
      {{ room_sync.total }}
      <small>(open here and closed in Rocket.Chat)</small>
      {% if room_sync.total %}
        <p class="mt-3">
          <a name=""
             class="btn btn-success"
             href="?check-room-sync=1&do-check-room-sync=1"
             role="button">sync!</a>
        </p>
      {% endif %}
    </div>
    <script>
      $(".alert").alert();
    </script>
  {% endif %}
  {% comment %} WPPCONNECT {% endcomment %}
  {% if connector.connector_type == "wppconnect" %}
    <div id="wppconnect">
      <div class="container">
        <p>
          <a name=""
             class="btn btn-primary"
             href="?connector=wppconnect&connector_action=status_session"
             role="button">get
          status</a>
          {% if connector_action_response.status_session.status != "CONNECTED" %}
            <a name=""
               class="btn btn-primary"
               href="?connector=wppconnect&connector_action=initialize"
               role="button">initialize</a>
          {% endif %}
          {% if connector_action_response.status_session.status == "CONNECTED" %}
            <a name=""
               class="btn btn-danger"
               href="?connector=wppconnect&connector_action=close_session"
               role="button">close session</a>
          {% endif %}
        </p>
      </div>
      {% if connector_action_response %}
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Connector Response</h4>
            <p class="card-text">
              {% if connector_action_response.initialize.qrcode and connector_action_response.status_session.status != "CONNECTED" %}
                <img src="{{ connector_action_response.initialize.qrcode }}" alt="QRCODE" />
              {% endif %}
              {% if connector_action_response.status_session.qrcode and connector_action_response.status_session.status != "CONNECTED" %}
                <img src="{{ connector_action_response.status_session.qrcode }}"
                     alt="QRCODE" />
              {% endif %}
              <pre>{{connector_action_response|pprint}}</pre>
            </p>
          </div>
        </div>
      {% endif %}
    </div>
  {% endif %}
  {% comment %} CODECHAT {% endcomment %}
  {% if connector.connector_type == "codechat" or connector.connector_type == "evolution" %}
    <div id="codechat">
      <div class="container">
        <p>
          <a name=""
             class="btn btn-primary"
             href="?connector=codechat&connector_action=status_session"
             role="button">get
          status</a>
          {% if connector_action_response.status_session.status != "CONNECTED" and connector_action_response.status_session.instance.status != "open" %}
            <a name=""
               class="btn btn-primary"
               href="?connector=codechat&connector_action=initialize"
               role="button">initialize</a>
          {% endif %}
          {% if connector_action_response.status_session.state == "open" or connector_action_response.status_session.instance.status == "open" %}
            <a name=""
               class="btn btn-danger"
               href="?connector=codechat&connector_action=close_session"
               role="button">close session</a>
          {% endif %}
        </p>
      </div>
      {% if connector_action_response %}
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Connector Response</h4>
            <p class="card-text">
              {% if connector_action_response.status_session.base64 %}
                <img src="{{ connector_action_response.status_session.base64 }}"
                     alt="QRCODE" />
              {% endif %}
              {% if connector_action_response.initialize.instance_connect.base64 %}
                <img src="{{ connector_action_response.initialize.instance_connect.base64 }}"
                     alt="QRCODE" />
              {% endif %}
              <pre>{{connector_action_response|pprint}}</pre>
            </p>
          </div>
        </div>
      {% endif %}
    </div>
  {% endif %}
  {% comment %} META CLOUD {% endcomment %}
  {% if connector.connector_type == "metacloudapi_whatsapp" %}
    <div id="metacloudapi_whatsapp">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Connector Response</h4>
          <p class="card-text">
            <pre>{{connector_action_response|pprint}}</pre>
          </p>
        </div>
      </div>
    </div>
  {% endif %}
  <hr />
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active"
         id="undelivered-messages-tab"
         data-bs-toggle="tab"
         data-bs-target="#undelivered-messages"
         href="#undelivered-messages"
         role="tab"
         aria-controls="undelivered-messages"
         aria-selected="true">Undelivered Messages</a>
    </li>
    {% if config_form %}
      <li class="nav-item">
        <a class="nav-link"
           id="configuration-tab"
           data-bs-toggle="tab"
           data-bs-target="#configuration"
           href="#configuration"
           role="tab"
           aria-controls="configuration"
           aria-selected="false">Configuration</a>
      </li>
    {% endif %}
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active"
         id="undelivered-messages"
         role="tabpanel"
         aria-labelledby="undelivered-messages-tab">
      <div id="undelivered_messages_by_day" class="container">
        <table class="table">
          <thead>
            <tr>
              <th>Date</th>
              <th>Undelivered Messages</th>
              <th>Rooms</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for message in messages_undelivered_by_date %}
              <tr>
                <td scope="row">{{ message.date|date:"SHORT_DATE_FORMAT" }}</td>
                <td>{{ message.created_count }}</td>
                <td>{{ message.room_count }}</td>
                <td>
                  <a name=""
                     class="btn btn-danger"
                     href="?date={{ message.date|date:'Y-m-d' }}&action=force_delivery"
                     role="button">force
                  delivery</a>
                  <a name=""
                     class="btn btn-success"
                     href="?date={{ message.date|date:'Y-m-d' }}&action=mark_as_delivered"
                     role="button">mark
                    as
                  delivered</a>
                  <a name=""
                     class="btn btn-info"
                     href="?date={{ message.date|date:'Y-m-d' }}&action=show"
                     role="button">show</a>
                </td>
              </tr>
            {% empty %}
              <tr>
                <td>
                  <i>No Undelivered Messages to show</i>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div id="undelivered_messages" class="container">
        {% if undelivered_messages %}
          <h1>Showing undelivered Messages for date {{ date|date:"SHORT_DATE_FORMAT" }}</h1>
          <hr />
          {% regroup undelivered_messages by room as undelivered_messages_by_room %}
          {% for rooms in undelivered_messages_by_room %}
            <div class="card mb-3">
              <div class="card-body">
                <h4 class="card-title">
                  <h2>
                    {% if rooms.grouper %}
                      {{ rooms.grouper }}
                      <a href="{{ rooms.list.0.connector.server.get_external_url }}//omnichannel/current/{{ rooms.grouper.room_id }}/room-info/">link
                      </a>
                    {% else %}
                      No Related Room
                    {% endif %}
                  </h2>
                </h4>
                <p class="card-text">
                  {% for message in rooms.list %}
                    <p>
                      <button class="btn btn-primary"
                              type="button"
                              data-bs-toggle="collapse"
                              href="#collapse-{{ message.id }}"
                              aria-expanded="false"
                              aria-controls="collapse-{{ message.id }}">{{ message.id }} {{ message.type }}</button>
                    </p>
                    <div class="collapse" id="collapse-{{ message.id }}">
                      <p class="clearfix text-center">
                        <a name=""
                           class="btn btn-danger"
                           href="?id={{ message.id }}&action=force_delivery"
                           role="button">force delivery</a>
                        <a name=""
                           class="btn btn-success"
                           href="?id={{ message.id }}&action=mark_as_delivered"
                           role="button">mark as delivered</a>
                      </p>
                      <div class="card card-body m-3">
                        <pre>{{message.raw_message|pprint}}</pre>
                      </div>
                    </div>
                  {% endfor %}
                </p>
              </div>
            </div>
          {% endfor %}
        {% endif %}
      </div>
    </div>
    <div class="tab-pane fade"
         id="configuration"
         role="tabpanel"
         aria-labelledby="configuration-tab">
      {% if config_form %}
        <div id="config" class="container mb-3">
          <h1>Configurations</h1>
          <form action="" method="post">
            {% csrf_token %}
            <p class="float-end">
              <button type="submit" class="btn btn-primary btn-lg btn-full">Save Configuration</button>
            </p>
            {{ config_form|crispy }}
            <p class="float-end">
              <button type="submit" class="btn btn-primary btn-lg btn-full">Save Configuration</button>
            </p>
          </form>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock content %}

rocket_connect/templates/instance/new_chatwoot_connector.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
  <nav class="breadcrumb">
    <a class="breadcrumb-item" href="{% url 'home' %}">home</a>
    <a class="breadcrumb-item"
       href="{% url 'instance:server_detail' server.external_token %}">
      <img src="{{ server.get_icon }}" width="20px" alt="server icon" />
    {{ server }}</a>
    <span class="breadcrumb-item active">New Chatwoot Connector</span>
  </nav>
  <div class="container p-5" id="server-header">
    <h1>
      {{ server }} <span class="text-{{ server.enabled|yesno:'success,danger' }}">{{ server.enabled|yesno:"Active,Inactive" }}</span>
    </h1>
    <hr />
  </div>
  <div id="form" class="container">
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
{% endblock content %}

rocket_connect/templates/instance/new_server.html
{% extends "base.html" %}

{% load crispy_forms_tags static %}

{% block content %}
  <nav class="breadcrumb">
    <a class="breadcrumb-item" href="{% url 'home' %}">home</a>
    <span class="breadcrumb-item active">New Server</span>
  </nav>
  <div id="form" class="container">
    <a name=""
       class="btn btn-light text-center"
       href="{% url 'instance:new_server_rocketchat' %}"
       role="button">
      <img src="{% static "images/rocket-chat-logo.svg" %}" width=100px alt="rocket chat logo" />
    </a>
    <a name=""
       class="btn btn-light text-center"
       href="{% url 'instance:new_server_chatwoot' %}"
       role="button">
      <img src="{% static "images/chatwoot-logo.svg" %}" width=100px alt="chatwoot logo" />
    </a>
  </div>
{% endblock content %}